### ISSUE TITLE
DynamicVoice Todo list

### ISSUE THREAD

**Issue by Kowlin** [Kowlin/refactored-cogs#26]
- [ ] Access management (Merge from #21)
- [ ] Position management (Core command and code is there, just need to build it in the logic)
- [ ] Command for the number of empty channels
- [ ] Internal errors

Merge from #23:

- Ability to set the naming scheme of dynamic voice channels (e.g. Rust Server # 3)
- Multiple groups of dynamic voice channels.  A gaming community might want dynamic Rust and Overwatch channels with their own independent settings.
- Ability to define settings by referencing an example voice channel.  For example, the admin might create a channel called Overwatch # 1, and that channel will have various permissions set up and limits on how many people can join it.  The admin could then type !dynamicvoice creategroup Overwatch and all those settings would be used to generate dynamic channels.
- Using that base channel, determine the position of new dynamic channels.

**Comment by jonyroda97** [comment]
Ability to set the maximum channels that can be created per group

**Comment by Kowlin** [comment]
I doubt I will work on DynamicVoice anymore now that it spams Audits logs even worse then my general rant in any coding channel on Red. Sorry :(
